# -*- coding: utf-8 -*-
#!/usr/bin/env python

"""
Indent Profiler: Console Interface
-------------------------------------------------------------------------------
Aaron Robertson
FRA
March 2018
-------------------------------------------------------------------------------
Program Description:
    main.py provides a console interface to control processing the data
that has been generated by the scanner.

Usage:
    TBD
-------------------------------------------------------------------------------
"""


#Libraries
import convert
import calibrate
import process
import fileIO
import utils

def main():
    
    #Stuff
    imports()
    
    fileIO.GetDir()
    fileIO.GetFile()    



'''Functions'''
'''-------------------------------------------------------------------------'''

def imports():
    #This is a temporary function. Delete it after you figure our dependency
    #handling
    
    import types
    print "\n"
    for name, val in globals().items():
        if isinstance(val, types.ModuleType):
            print val.__name__




if __name__ == "__main__":
    main()