# -*- coding: utf-8 -*-
#!/usr/bin/env python

"""
Indent Profiler: Console Interface
-------------------------------------------------------------------------------
Aaron Robertson
FRA
March 2018
-------------------------------------------------------------------------------
Program Description:
    main.py provides a console interface to control processing the data
that has been generated by the scanner.

Usage:
    TBD
-------------------------------------------------------------------------------
"""


#Libraries
import convert
import calibrate
import process
import fileIO
import utils

def main():
    Test()
    
    #Stuff
    import types
    def imports():
        print "\n"
        for name, val in globals().items():
            if isinstance(val, types.ModuleType):
                print val.__name__
    imports()



'''Functions'''
'''-------------------------------------------------------------------------'''
def Test():
    import numpy as np
    return 0




if __name__ == "__main__":
    main()