# -*- coding: utf-8 -*-
#!/usr/bin/env python

"""
Indent Profiler: Consoler Interface
-------------------------------------------------------------------------------
Aaron Robertson
FRA
March 2018
-------------------------------------------------------------------------------
Program Description:
    main.py provides a console interface to control processing the data
that has been generated by the scanner.

Usage:
    TBD
-------------------------------------------------------------------------------
"""


#Libraries
import convert
import calibrate
import process
import fileIO
import utils

def main():








if __name__ == "__main__":
    main()
